spring:
  datasource:
    url: jdbc:mysql://localhost:3306/exam?useUnicode=true&characterEncoding=gbk&autoReconnect=true&failOverReadOnly=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  mail:
    host: smtp.qq.com
    protocol: smtp
    username:
    password:
    port:
    default-encoding: UTF-8
  data:
    redis:
      timeout: 3000
      database: 0
      password:
      port: 6379
      host: localhost
logging:
  level:
    org: debug
server:
  port: 8088